<?php

namespace AppBundle\Repository;

/**
 * BotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BotRepository extends \Doctrine\ORM\EntityRepository
{
}
