<?php

namespace AppBundle\Repository;

use AppBundle\Entity\BotUserMessage;
use AppBundle\Entity\BotVocabulary;
use AppBundle\Entity\Message;

/**
 * BotUserMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BotUserMessageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param BotVocabulary $botVocabulary
     * @param Message       $message
     *
     * @return BotUserMessage
     */
    public function createBotUserMessage(BotVocabulary $botVocabulary, Message $message)
    {

        $botUserMessage = new BotUserMessage();

        $botUserMessage->setBot($botVocabulary->getBot());
        $botUserMessage->setMessage($message);

        $answer = $botVocabulary->getAnswer();

        //@todo create method to check answer and return result in service
        if ($botVocabulary->getAction() == 'execute' && $botVocabulary->getAnswer() == 'current-time'){
            $answer = (new \DateTime('now'))->format('H:i');
        }

        $botUserMessage->setAnswerMessage($answer);
        $em = $this->getEntityManager();
        $em->persist($botUserMessage);
        $em->flush();
        return $botUserMessage;
    }

}
