<?php

namespace AppBundle\Repository;

/**
 * BotVocabluaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BotVocabularyRepository extends \Doctrine\ORM\EntityRepository
{
}
