<?php

namespace AppBundle\Repository;

/**
 * ChatPrticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatParticipantRepository extends \Doctrine\ORM\EntityRepository
{
}
