<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Message;
use AppBundle\Entity\User;

/**
 * MessageRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param  User $user
     *
     * @return Message[]
     */
    public function getUserMessages(User $user): array
    {
        $qb = $this->createQueryBuilder('m')
                   ->select('m')
                   ->leftJoin('m.botUserMessage', 'bum')
                   ->where('m.userId = :userId')
                   ->setParameter('userId', $user->getId());

        $qb->orderBy('m.createdAt', 'desc');

        $messages = $qb->getQuery()->getResult();

        return $messages;
    }

    /**
     * @param Message $message
     * @param User   $user
     *
     * @return Message
     */
    public function createUserMessage(Message $message, User $user)
    {

        $message->setUserId($user->getId());
        $message->setCreatedAt(new \DateTime('now'));
        $em = $this->getEntityManager();
        $em->persist($message);
        $em->flush();
        return $message;
    }
}
